apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckan-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckan-worker
  template:
    metadata:
      labels:
        app: ckan-worker
        app.kubernetes.io/part-of: ckan
    spec:
      containers:
      - name: ckan-worker
        image: quay.io/incineroar/ckan-base:5.8
        envFrom:
        - configMapRef:
            name: ckan-worker-config
        - secretRef:
            name: ckan-secret
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
