apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckan
  template:
    metadata:
      labels:
        app: ckan
        app.kubernetes.io/part-of: ckan
    spec:
      containers:
        - name: ckan
          image: quay.io/incineroar/ckan-base:6.5
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: ckan-config
            - secretRef:
                name: ckan-secret
          volumeMounts:
            - name: ckan-storage
              mountPath: /var/lib/ckan
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: ckan-storage
          persistentVolumeClaim:
            claimName: ckan-storage

---

apiVersion: v1
kind: Service
metadata:
  name: ckan
  labels:
    app: ckan
spec:
  ports:
    - name: http
      port: 5000          # The port the service exposes internally
      targetPort: 5000    # Must match the CKAN container port
  selector:
    app: ckan